apiVersion: v1
kind: Service
metadata:
  name: qamysqldb ## VERY VERY IMPORTANT - NGINX PROXYPASS needs this name
  labels:
    app: vprofile-db
    tier: backend   
spec:
  #type: ClusterIP is a default service in k8s
  selector:
    app: vprofile-db
  ports:
    - name: http
      port: 3306 # ClusterIP Service Port
      targetPort: 3306 # Container Port