apiVersion: v1
kind: Service 
metadata:
  name: vprofile-app-loadbalancer-service
  labels:
    app: vprofile-app
    tier: frontend  
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: vprofile-app
  ports: 
    - name: http
      port: 8080 # Service Port
      targetPort: 8080 # Container Port