apiVersion: v1
kind: Service 
metadata:
  name: vprofile-app-loadbalancer-service
  labels:
    app: vprofile-nginx
    tier: frontend  
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: vprofile-nginx
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port