apiVersion: v1
kind: Service
metadata:
  name: vproapp ## VERY VERY IMPORTANT - NGINX PROXYPASS needs this name
  labels:
    app: vprofile-app
    tier: backend   
spec:
  #type: ClusterIP is a default service in k8s
  selector:
    app: vprofile-app
  ports:
    - name: http
      port: 8080 # ClusterIP Service Port
      targetPort: 8080 # Container Port