apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-app-deployment
  labels:
    app: vprofile-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprofile-app
  template:
    metadata:
      labels:
        app: vprofile-app
    spec:
      containers:
        - name: vprofile-nginx
          image: pranay05/vproapp:241
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # Requests & Limits   
          resources:
            requests:
              cpu: "100m" 
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
