pool:
  name: Hosted VS2017

resources:
  repositories:
    - repository: other
      type: git
      name: Java Project/Vprofile

stages:

- stage: build
  displayName: Build
  jobs:
  - job: Build
    steps:
    - checkout: self
    - checkout: other
    - task: Maven@3
      inputs:
        mavenPomFile: '$(System.DefaultWorkingDirectory)\Vprofile\pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: WhiteSource@21
      inputs:
        cwd: '$(System.DefaultWorkingDirectory)\Vprofile'
        projectName: 'Vprofile'