parameters:
  - name: my_array_param
    default: ['QA', 'STG']
    type: object

stages:
- ${{each thing in parameters.my_array_param}}:
- stage: build
  displayName: Build
  variables: 
  - group: ${{ parameters.Environments }}Vprofile
      