parameters:
  - name: my_array_param
    default: ['QA', 'STG']
    type: object
jobs:
- ${{each thing in parameters.my_array_param}}:
  - job: 
    steps:
    - pwsh: Write-Output "hello word"
      