pool:
  vmImage: 'ubuntu-latest'
  demands: 'curl'
resources:
  repositories:
    - repository: other
      type: git
      name: Java Project/Vprofile

parameters:
  - name: Environments
    default: ['QA', 'STG']
    type: object

  - name: AppVm
    default: null
      - APPVM

  - name: WebVm
    default: null
      - WEBVM

  - name: MysqlVm
    default: null
      - MySQLVM

  - name: CacheVm
    default: null 
      - CacheVM

stages:

- stage: Build 
  displayName: Build
#   #variables: 
#  #- group: ${{parameters.Environments }}Vprofile
 
  jobs:
  - ${{each env in parameters.Environments}}:
    - template: Mutistage/BUILDmultistage.yml
      
      parameters:
        Environments: ${{env}}
        dependsOn: ${{env}}

- stage: QA_InfraCreation_Release
  displayName: Infrasetup and Release
  dependsOn: Build
  variables: 
  - group: QAVprofile
  
  jobs:
  
    - job: InfrasetupQA
      displayName: InfrasetUP
    - template: Mutistage/Inframultistage.yml
      parameters:
        Environments: QA
        AppVm: ${{ parameters.AppVm }}
        WebVm: ${{ parameters.WebVm }}
        MysqlVm: ${{ parameters.MysqlVm }}
        CacheVm: ${{ parameters.CacheVm }}
    - job: Release
      displayName: ReleaseQA
      dependsOn: Infrasetup
    - template: Mutistage/Releasemultistage.yml

# - stage: STG_InfraCreation_Release
#   displayName: Infrasetup and Release
#   dependsOn: Build
#   variables: 
#   - group: STGVprofile
  
#   jobs:
  
#     - job: InfrasetupSTG
#       displayName: InfrasetUP
#     - template: Mutistage/Inframultistage.yml
#       parameters:
#         Environments: STG
#         AppVm: ${{ parameters.AppVm }}
#         WebVm: ${{ parameters.WebVm }}
#         MysqlVm: ${{ parameters.MysqlVm }}
#         CacheVm: ${{ parameters.CacheVm }}
#     - job: ReleaseSTG
#       displayName: Release
#       dependsOn: Infrasetup
#     - template: Mutistage/Releasemultistage.yml

# - stage: Release
#   displayName: Release
#   variables: 
#   - group: ${{ parameters.Environments }}Vprofile
  
#   jobs:
#   - template: Templates/Release.yml

    