parameters:
  - name: my_array_param
    default: ['qa', 'stg']
    type: object

jobs:
- ${{each thing in parameters.my_array_param}}:
  - job: 
    steps:
    - task: CmdLine@2
      displayName: Log Parameters
      inputs:
       script: |
        echo my_array_param: ${{join(' ',parameters.my_array_param)}}