parameters:
  - name: my_array_param
    default: ['entry1', 'entry2']
    type: object

jobs:
  - job: 
    steps:
    - task: CmdLine@2
      displayName: Log Parameters
      inputs:
       script: |
        echo my_array_param: ${{join(' ',parameters.my_array_param)}}