pool:
  vmImage: 'ubuntu-latest'
  demands: 'curl'
resources:
  repositories:
    - repository: other
      type: git
      name: Java Project/Vprofile

parameters:
  - name: Environments
    displayName: Select Environment
    default: QA
      - QA
      - STG
      - PROD  
  - name: listToDeploy
    displayName: Select in the list
    default: ["APPVM","WEBVM","MySQLVM","CacheVM"]
stages:

- stage: build
  displayName: Build
  variables: 
  - group: ${{ parameters.Environments }}Vprofile
 
  jobs:
  - template: Templates/BUILD.yml

- stage: InfraCreation
  displayName: Infrasetup
  variables: 
  - group: ${{ parameters.Environments }}Vprofile
  
  jobs:
  - template: Templates/Infra.yml
  
- stage: Release
  displayName: Release
  variables: 
  - group: ${{ parameters.Environments }}Vprofile
  
  jobs:
  - template: Templates/Release.yml

    