pool:
  vmImage: 'ubuntu-latest'
  demands: 'curl'
resources:
  repositories:
    - repository: other
      type: git
      name: Java Project/Vprofile

parameters:
  - name: Environments
    displayName: Select Environment
    default: QA
      - QA
      - STG
      - PROD  

stages:

- stage: build
  displayName: Build
  variables: 
  - group: ${{ parameters.Environments }}Vprofile
 
  jobs:
  - template: Templates/BUILD.yml

- stage: InfraCreation
  displayName: Infrasetup
  variables: 
  - group: ${{ parameters.Environments }}Vprofile
  
  jobs:
  - template: Templates/Infra.yml
  
- stage: Release
  displayName: Release
  variables: 
  - group: ${{ parameters.Environments }}Vprofile
  
  jobs:
  - job: Release
    steps:
    - checkout: self    
    - checkout: other
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        itemPattern: '**/vprofile-v2.war'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: CmdLine@2
      inputs:
        script: 'ls "/home/vsts/work/1/a/Vprofile/target"'
    - task: TomcatDeployment@1
      inputs:
        TomcatUrl: 'http://webvmeusqavprofile.eastus.cloudapp.azure.com:8080'
        Username: 'tomcat'
        Password: 'admin123'
        Warfile: '$(System.ArtifactsDirectory)/Vprofile/target/vprofile-v2.war'
        Context: '/v2'
        ServerVersion: '7OrAbove'

    