trigger:
- none

pool:
  vmImage: 'windows-latest'

resources:
 repositories:
     - repository: Vprofile
       type: git
       name: Java Project/Vprofile

parameters:
- name: Environments
  displayName: ENVIRONMENTS
  values:
      - QA
      - KLO
      - STG

stages:
    - stage: BUILD
      jobs:
          - job: build
            steps:
              - checkout: "Vprofile"
              - task: Maven@3
                inputs:
                  mavenPomFile: 'pom.xml'
                  publishJUnitResults: true
                  testResultsFiles: '**/surefire-reports/TEST-*.xml'
                  javaHomeOption: 'JDKVersion'
                  mavenVersionOption: 'Default'
                  mavenAuthenticateFeed: false
                  effectivePomSkip: false
                  sonarQubeRunAnalysis: false
              - task: PowerShell@2
                inputs:
                  targetType: 'inline'
                  script: |
                    $Config_path = "C:\Users\M1051583\Downloads\application.properties"
                    $Contents = get-content $Config_path 
                    $ChangedValues = $Contents -replace "dbinstance", "dbserver"
                    $ChangedValues = $ChangedValues -replace "dbname", "dbusername"
                    $ChangedValues = $ChangedValues -replace "dbname123", "dbpassword"
                    $ChangedValues > $Config_path
