trigger:
- none

pool:
  vmImage: 'windows-latest'

resources:
 repositories:
     - repository: Vprofile
       type: git
       name: Java Project/Vprofile

parameters:
- name: Environments
  displayName: ENVIRONMENTS
  values:
      - QA
      - KLO
      - STG

stages:
    - stage: BUILD
      jobs:
          - job: build
            steps:
              - checkout: "Vprofile"
              - task: Maven@3
                inputs:
                  mavenPomFile: 'pom.xml'
                  publishJUnitResults: true
                  testResultsFiles: '**/surefire-reports/TEST-*.xml'
                  javaHomeOption: 'JDKVersion'
                  mavenVersionOption: 'Default'
                  mavenAuthenticateFeed: false
                  effectivePomSkip: false
                  sonarQubeRunAnalysis: false
