trigger:
- none

pool:
  vmImage: 'windows-latest'

resources:
 repositories:
     - repository: Vprofile
       type: git
       name: Java Project/Vprofile

parameters:
- name: Environments
  displayName: ENVIRONMENTS
  values:
      - QA
      - KLO
      - STG

stages:
    - stage: BUILD
      jobs:
          - job: build
            steps:
              - checkout: "Vprofile"
              - task: PowerShell@2
                inputs:
                  targetType: 'inline'
                  script: |
                    $Config_path = "$(System.DefaultWorkingDirectory)/src/main/resources/application.properties"
                    $Contents = get-content $Config_path 
                    $ChangedValues = $Contents -replace "dbservername", "KLOdb"
                    $ChangedValues = $ChangedValues -replace "dbusername", "KLOusername"
                    $ChangedValues = $ChangedValues -replace "dbpassword", "KLOpassword"
                    $ChangedValues > $Config_path
              - task: Maven@3
                inputs:
                  mavenPomFile: 'pom.xml'
                  publishJUnitResults: true
                  testResultsFiles: '**/surefire-reports/TEST-*.xml'
                  javaHomeOption: 'JDKVersion'
                  mavenVersionOption: 'Default'
                  mavenAuthenticateFeed: false
                  effectivePomSkip: false
                  sonarQubeRunAnalysis: false
                  checkStyleRunAnalysis: true
                  pmdRunAnalysis: true
                  findBugsRunAnalysis: true
              - task: CopyFiles@2
                inputs:
                  SourceFolder: '$(System.DefaultWorkingDirectory)/src/main/resources/application.properties'
                  Contents: '**'
                  TargetFolder: '$(Build.ArtifactStagingDirectory)'
              - task: PowerShell@2
                inputs:
                  targetType: 'inline'
                  script: 'ls $(System.DefaultWorkingDirectory)/target'
              - task: CopyFiles@2
                inputs:
                  SourceFolder: '$(System.DefaultWorkingDirectory)/target/vprofile-v2.war'
                  Contents: '**'
                  TargetFolder: '$(Build.ArtifactStagingDirectory)'
              - task: PublishBuildArtifacts@1
                inputs:
                  PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                  ArtifactName: 'drop'
                  publishLocation: 'Container'
              